apiVersion: v1
kind: Service
metadata:
  name: chat-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:ap-northeast-2:068149769006:certificate/dde95b2e-4ad3-4a67-8759-a81896270272
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: (https|http|ssl|tcp)
  labels:
    app: chat
    service: chat
spec:
  ports:
    - port: 80
      targetPort: 80
      name: http
    - port: 443
      targetPort: 443
      name: tls
  selector:
    app: chat
  type: LoadBalancer
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: streetvendor-chat
  labels:
    account: chat
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-v1
  labels:
    app: chat
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat
      version: v1
  template:
    metadata:
      labels:
        app: chat
        version: v1
    spec:
      serviceAccountName: streetvendor-chat
      containers:
        - name: chat
          image: holicker0601/chat:2.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: 350Mi
