apiVersion: v1
kind: Service
metadata:
  name: chat-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:ap-northeast-2:068149769006:certificate/7929495f-7537-4a58-a3a1-905c1abe33b2
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: https
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "3600"
  labels:
    app: chat
    service: chat
spec:
  ports:
    - port: 80
      targetPort: 80
      name: http
    - port: 443
      targetPort: 80
      name: https
  selector:
    app: chat
  type: LoadBalancer
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: streetvendor-chat
  labels:
    account: chat
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-v1
  labels:
    app: chat
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat
      version: v1
  template:
    metadata:
      labels:
        app: chat
        version: v1
    spec:
      serviceAccountName: streetvendor-chat
      containers:
      - name: chat
        image: holicker0601/chat:2.7
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 80
        resources:
          limits:
            memory: 350Mi
        env:
        - name: SPRING_CONFIG_LOCATION
          value: file:/config/application.yaml
        envFrom:
        - secretRef:
            name: mysql-credentials
        volumeMounts:
        - name: config-repo-volume
          mountPath: /config
      volumes:
      - name: config-repo-volume
        configMap:
          name: config-repo
