apiVersion: v1
kind: Service
metadata:
  name: front
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:ap-northeast-2:068149769006:certificate/b05255ee-b97a-41a7-9320-c6dbce031ae8
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: https
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "3600"
  labels:
    app: front
    service: front
spec:
  ports:
    - port: 80
      targetPort: 3000
      name: http
    - port: 443
      name: https
      targetPort: 3000
  selector:
    app: front
  type: LoadBalancer

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: streetvendor-front
  labels:
    account: front
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-v1
  labels:
    app: front
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front
      version: v1
  template:
    metadata:
      labels:
        app: front
        version: v1
    spec:
      serviceAccountName: streetvendor-front
      containers:
        - name: front
          image: holicker0601/front:0.9
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: 350Mi
          env:
            - name: REACT_APP_AUTH
              value: https://www.streetvendor.co.kr/app/auth
            - name: REACT_APP_NOTICE
              value: https://www.streetvendor.co.kr/app/notice
            - name: REACT_APP_REVIEW
              value: https://www.streetvendor.co.kr/app/review
            - name: REACT_APP_QNA
              value: https://www.streetvendor.co.kr/app/qna
            - name: REACT_APP_VENDOR
              value: https://www.streetvendor.co.kr/app/vendor
            - name: REACT_APP_CHAT
              value: https://wss.streetvendor.co.kr
            - name: REACT_APP_WEBSCOKET
              value: https://wss.streetvendor.co.kr
