apiVersion: v1
kind: Service
metadata:
  name: front
  labels:
    app: front
    service: front
spec:
  ports:
    - port: 3000
      name: http
  selector:
    app: front
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: streetvendor-front
  labels:
    account: front
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-v1
  labels:
    app: front
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front
      version: v1
  template:
    metadata:
      labels:
        app: front
        version: v1
    spec:
      serviceAccountName: streetvendor-front
      containers:
        - name: front
          image: holicker0601/front:0.8
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: 350Mi
          env:
            - name: REACT_APP_AUTH
              value: http://auth
            - name: REACT_APP_CHAT
              value: http://chat-service
            - name: REACT_APP_NOTICE
              value: http://notice
            - name: REACT_APP_REVIEW
              value: http://review
            - name: REACT_APP_QNA
              value: http://qna
            - name: REACT_APP_VENDOR
              value: http://vendor
