apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: streetvendor-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: streetvendor
spec:
  hosts:
    - "*"
  gateways:
    - streetvendor-gateway
  http:
    - match:
        - uri:
            exact: /vendor
      route:
        - destination:
            host: vendor
            port:
              number: 80
