apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: wurstmeister/kafka:2.12-2.1.0
          env:
            - name: KAFKA_ADVERTISED_HOST_NAME
              value: kafka
            - name: KAFKA_ADVERTISED_PORT
              value: "9092"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zookeeper:2181
            - name: KAFKA_CREATE_TOPICS
              value: katka-chatting:1:1
          ports:
            - containerPort: 9092
          resources:
            limits:
              memory: 350Mi

---
apiVersion: v1
kind: Service
metadata:
  name: kafka
spec:
  ports:
    - port: 80
      targetPort: 9092
      name: http
  selector:
    app: kafka
  type: LoadBalancer
