apiVersion: v1
kind: Service
metadata:
  name: notice
  labels:
    app: notice
    service: notice
spec:
  selector:
    app: notice
  ports:
    - port: 80
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: streetvendor-notice
  labels:
    account: notice
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notice
  template:
    metadata:
      labels:
        app: notice
    spec:
      serviceAccountName: streetvendor-notice
      containers:
        - name: notice
          image: holicer0601/notice:0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: 350Mi

