apiVersion: v1
kind: Service
metadata:
  name: notice
  labels:
    app: notice
    service: notice
spec:
  ports:
    - port: 80
      targetPort: 80
      name: http
  selector:
    app: notice
  type: LoadBalancer
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: streetvendor-notice
  labels:
    account: notice
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notice-v1
  labels:
    app: notice
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notice
      version: v1
  template:
    metadata:
      labels:
        app: notice
        version: v1
    spec:
      serviceAccountName: streetvendor-notice
      containers:
        - name: notice
          image: holicker0601/notice:0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: 350Mi
