apiVersion: v1
kind: Service
metadata:
  name: qna
  labels:
    app: qna
    service: qna
spec:
  ports:
    - port: 80
      name: http
  selector:
    app: qna
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: streetvendor-qna
  labels:
    account: qna
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qna-v1
  labels:
    app: qna
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qna
      version: v1
  template:
    metadata:
      labels:
        app: qna
        version: v1
    spec:
      serviceAccountName: streetvendor-qna
      containers:
        - name: qna
          image: holicker0601/qna:0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: 350Mi
