apiVersion: v1
kind: Service
metadata:
  name: review
  labels:
    app: review
    service: review
spec:
  selector:
    app: review
  ports:
    - port: 80
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: streetvendor-review
  labels:
    account: review
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: review
spec:
  replicas: 1
  selector:
    matchLabels:
      app: review
  template:
    metadata:
      labels:
        app: review
    spec:
      serviceAccountName: streetvendor-review
      containers:
        - name: review
          image: holicer0601/review:0.0
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: 350Mi

