apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
        - name: zookeeper
          image: wurstmeister/zookeeper:3.4.6
          env:
            - name: KAFKA_ADVERTISED_HOST_NAME
              value: zookeeper
          ports:
            - containerPort: 2181
          resources:
            limits:
              memory: 350Mi

---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
spec:
  ports:
    - port: 80
      targetPort: 2181
      name: http
  selector:
    app: zookeeper
  type: LoadBalancer
