server.port: 80
server.error.include-message: always

spring.application.name: vendor

spring.jpa.hibernate.ddl-auto: update

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver

management.endpoint.health.show-details: "ALWAYS"
management.endpoints.web.exposure.include: "*"

cors.hostname: http://localhost:3000

kafka.profiles: kafka-service:9092

grpc:
  hostname: detail-service
  port: 7000